export const RedisQueueSpreadsheetConstant = {
  NAME: 'spreadsheet',
  SAVE_INCOME_TAX_AGGREGATED_DATA: 'INCOME_TAX_AGGREGATED_DATA',
  SAVE_CALCULATE_DATA: 'SAVE_CALCULATE_DATA',
  // Notice: 'Notice',
  // IncomePaymentWithholding: 'IncomePaymentWithholding',
  // IncomePaymentYearEndSettlement: 'IncomePaymentYearEndSettlement',
  // IncomePaymentEarning: 'IncomePaymentEarning',
  // IncomePaymentEtc: 'IncomePaymentEtc',
  // YearEndSettlementCard: 'YearEndSettlementCard',
  // YearEndSettlementCashReceipt: 'YearEndSettlementCashReceipt',
  // YearEndSettlementCheckCard: 'YearEndSettlementCheckCard',
  // YearEndSettlementCreditCard: 'YearEndSettlementCreditCard',
  // YearEndSettlementDonation: 'YearEndSettlementDonation',
  // YearEndSettlementEducationExpense: 'YearEndSettlementEducationExpense',
  // YearEndSettlementHealthInsurance: 'YearEndSettlementHealthInsurance',
  // YearEndSettlementHouseMortgageLoan: 'YearEndSettlementHouseMortgageLoan',
  // YearEndSettlementHouseRentalLoan: 'YearEndSettlementHouseRentalLoan',
  // YearEndSettlementInsurance: 'YearEndSettlementInsurance',
  // YearEndSettlementMedicalExpense: 'YearEndSettlementMedicalExpense',
  // YearEndSettlementMedicalInsurance: 'YearEndSettlementMedicalInsurance',
  // YearEndSettlementPaymentDonationCarryOver: 'YearEndSettlementPaymentDonationCarryOver',
  // YearEndSettlementPensionSaving: 'YearEndSettlementPensionSaving',
  // YearEndSettlementSchoolUniformExpense: 'YearEndSettlementSchoolUniformExpense',
  // YearEndSettlementStudentLoan: 'YearEndSettlementStudentLoan',
  // YearEndSettlementSupportFamily: 'YearEndSettlementSupportFamily',
  // YearEndSettlementVocationTrainingExpense: 'YearEndSettlementVocationTrainingExpense',
};
